AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Resources for MyNextBook backend


Resources:
  # API GATEWAY
  MyNextBookAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
  # LAMBDA
  GetCategoryRecommendations:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 30
      CodeUri: src/
      Description: Get recommendations from categories of interest
      Handler: lambdas.recommendations.app
      Runtime: python3.9
      Events:
        PostModel:
          Type: Api
          Properties:
            RestApiId: !Ref MyNextBookAPI
            Path: /category_recommendations
            Method: get
      Role: !GetAtt ReadAPIKeys.Arn
  # ROLES
  ReadAPIKeys:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: LambdaPolicies
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - ssm:GetParameter
                Effect: Allow
                Resource: arn:aws:ssm:eu-west-1:438998290379:parameter/open_ai_key
        - PolicyName: GoogleBooksLambdaPolicies
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - ssm:GetParameter
                Effect: Allow
                Resource: arn:aws:ssm:eu-west-1:438998290379:parameter/google_books_key