AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Resources for MyNextBook backend


Resources:
  # API GATEWAY
  MyNextBookAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
  # BUCKETS
  CategoryBucket:
    Type: AWS::S3::Bucket
    Description: Bucket to store user category preferences
    Properties:
      BucketName: user-category-bucket
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  # LAMBDA
  GetCategoryRecommendations:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 30
      CodeUri: src/
      Description: Get recommendations from categories of interest
      Handler: lambdas.recommendations.app.get_category_recommendations
      Runtime: python3.9
      Events:
        GetRecommendations:
          Type: Api
          Properties:
            RestApiId: !Ref MyNextBookAPI
            Path: /category_recommendations
            Method: get
      Role: !GetAtt LambdaRole.Arn
  GetUserSelectedCategories:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 30
      CodeUri: src/
      Description: Get user chosen category preferences
      Handler: lambdas.recommendations.app.get_user_selected_categories
      Runtime: python3.9
      Events:
        GetRecommendations:
          Type: Api
          Properties:
            RestApiId: !Ref MyNextBookAPI
            Path: /user_selected_categories
            Method: get
      Role: !GetAtt LambdaRole.Arn
  GetRecommendationsFromBook:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 30
      CodeUri: src/
      Description: Get recommendations for similar books
      Handler: lambdas.recommendations.app.get_recommendations_from_book
      Runtime: python3.9
      Events:
        GetRecommendations:
          Type: Api
          Properties:
            RestApiId: !Ref MyNextBookAPI
            Path: /recommendations_from_book
            Method: get
      Role: !GetAtt LambdaRole.Arn
  GetCategories:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 30
      CodeUri: src/
      Description: Get book categories
      Handler: lambdas.categories.app.get_categories
      Runtime: python3.9
      Events:
        GetRecommendations:
          Type: Api
          Properties:
            RestApiId: !Ref MyNextBookAPI
            Path: /categories
            Method: get
      Role: !GetAtt LambdaRole.Arn
  PostCategories:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 30
      CodeUri: src/
      Description: Store user category preferences
      Handler: lambdas.categories.app.post_categories
      Runtime: python3.9
      Environment:
        Variables:
          CategoryBucket: !Ref CategoryBucket
      Events:
        PostModel:
          Type: Api
          Properties:
            RestApiId: !Ref MyNextBookAPI
            Path: /categories
            Method: post
      Role: !GetAtt LambdaRole.Arn
  # ROLES
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: GetOpenAPIKey
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - ssm:GetParameter
                Effect: Allow
                Resource: arn:aws:ssm:eu-west-1:438998290379:parameter/open_ai_key
        - PolicyName: GetGoogleBooksKey
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - ssm:GetParameter
                Effect: Allow
                Resource: arn:aws:ssm:eu-west-1:438998290379:parameter/google_books_key
        - PolicyName: S3Access
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:SelectObjectContent
                Effect: Allow
                Resource:
                  - !Sub ${CategoryBucket.Arn}
                  - !Sub ${CategoryBucket.Arn}/*
        - PolicyName: CloudWatchAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*