import json

# book_categories = {
#     "Fiction": [
#         "Romance 💕",
#         "Science Fiction 🚀",
#         "Fantasy 🧚️",
#         "Mystery 🕵️️",
#         "Historical Fiction 🏰",
#         "Thriller 💥",
#         "Horror 👻",
#         "Drama 🎭",
#         "Comedy 😆",
#         "Crime 💰",
#         "Western 🤠",
#         "Short Story 📖",
#         "Classic 🧐",
#         "Contemporary 🕰️",
#         "LGBTQ+ Fiction 🏳️‍🌈",
#     ],
#     "Non-Fiction": [
#         "Biography 📖",
#         "History 🏛️",
#         "Science 🧪",
#         "Self-help 💪",
#         "Travel 🧳",
#         "Memoir 💭",
#         "Business 💼",
#         "Health and Wellness 🧘️",
#         "Cooking 🍴",
#         "Religion and Spirituality 🙏",
#         "Philosophy 🤔",
#         "Political Science 🗳️",
#         "Economics 💰",
#         "Journalism 📰",
#         "Education 🎓",
#         "Parenting 👪",
#         "Art 🎨",
#     ],
#     "Children's Books": [
#         "Picture Books 🖼️",
#         "Chapter Books 📚",
#         "Young Adult 🧔",
#         "Non-Fiction 💡",
#         "Board Books 📖",
#         "Early Readers 💡",
#         "Middle-Grade 🧒",
#         "Graphic Novels 📖",
#         "Poetry 💭",
#         "Activity Books 🎨",
#         "Coloring Books 🎨",
#         "Fairy Tales 🧚",
#         "Mythology 🧝",
#         "Folklore 👴️",
#     ],
#     "Educational": [
#         "Textbooks 📚",
#         "Study Guides 📚",
#         "Workbooks 💻",
#         "Test Prep 📊",
#         "Language Learning 🌎",
#         "Academic 🎓",
#         "Entrance Exam 🎓",
#         "Certification Exam 💼",
#         "College Guides 🎓",
#         "Career Guides 💼",
#         "Graduate School Guides 🎓",
#     ],
#     "Professional and Technical": [
#         "Medicine 💊",
#         "Law 💼",
#         "Business 💼",
#         "Engineering 🛠️",
#         "Computer Science 💻",
#         "Architecture 🏢",
#         "Agriculture 🌾",
#         "Environmental Science 🌍",
#         "Mathematics 🔢",
#         "Physics 🔬",
#         "Chemistry 🧪",
#         "Biology 🧬",
#         "Geography 🗺️",
#         "Astronomy 🚀",
#         "Earth Science 🌎",
#         "Social Science 🧠",
#     ],
#     "Poetry": [
#         "Classical Poetry 🎭",
#         "Modern Poetry 🎨",
#         "Haiku 🌿",
#         "Sonnet 🎶",
#         "Free verse 🎵",
#     ],
#     "Photography": [
#         "Landscape 🏞️",
#         "Portrait 📸",
#         "Wildlife 🐘",
#         "Action 💥",
#         "Street 🚶️",
#         "Fine Art 🎨",
#         "Commercial 💰",
#         "Underwater 🌊",
#         "Aerial 🛩️",
#         "Astrophotography 🌌",
#     ],
#     "Art": [
#         "Painting 🎨",
#         "Sculpture 💎",
#         "Drawing 🖍️",
#         "Printmaking 📰",
#         "Photography 📷",
#     ],
#     "Religion and Spirituality": [
#         "Buddhism 🧘",
#         "Christianity ✝️",
#         "Islam 🕋",
#         "Hinduism 🙏",
#         "Judaism 🕎",
#         "New Age 🌟",
#     ],
#     "Science": [
#         "Physics 🔬",
#         "Chemistry 🧪",
#         "Biology 🔬",
#         "Astronomy 🌌",
#         "Earth Science 🌍",
#         "Environmental Science 🌿",
#         "Technology 💻",
#         "Mathematics 📚",
#         "Computer Science 💻",
#     ],
#     "Sports and Recreation": [
#         "Fitness 🏋️️",
#         "Outdoor 🏕️",
#         "Team Sports 🏀",
#         "Individual Sports 🎾",
#         "Coaching 🏋️️",
#         "Extreme Sports 💥",
#         "Water Sports 🏊️",
#         "Winter Sports ⛷️",
#         "Equestrian 🐴",
#     ],
#     "Comics and Graphic Novels": [
#         "Superhero 🦸️",
#         "Science Fiction 🚀",
#         "Fantasy 🧝️",
#         "Historical 🏰",
#         "Horror 👻",
#     ],
#     "Cookbooks": [
#         "Regional 🌍",
#         "Cuisine 🍲",
#         "Special Diet 🥦",
#         "Cooking Techniques 🍴",
#         "Chefs 🧑🍳",
#     ],
#     "Crafts and Hobbies": [
#         "Needlework 🧵",
#         "Woodworking 🔨",
#         "Home Improvement 🏠",
#         "Paper Craft 📝",
#         "Beading 💎",
#     ],
#     "Dictionaries and Encyclopedias": [
#         "General 📚",
#         "Specialized 💡",
#         "Foreign Language 🌎",
#         "Medical 💉",
#         "Technical 💻",
#     ],
#     "Entertainment": ["Music 🎶", "Movies 🎥", "Television 📺", "Awards 🎭", "Humor 😂"],
#     "Gay and Lesbian": [
#         "Fiction 📖",
#         "Nonfiction 📚",
#         "Poetry 🖋️",
#         "Biography 🧔",
#         "Autobiography 💬",
#     ],
#     "Health and Medicine": [
#         "Diseases 🦠",
#         "Disorders 🤕",
#         "Drug Guides 💊",
#         "First Aid 🚑",
#         "Health Policy 💊",
#     ],
#     "History": [
#         "World 🌍",
#         "European 🇪🇺",
#         "American 🇺🇸",
#         "Ancient 🏺",
#         "Medieval 🏰",
#         "Military 💂️",
#     ],
#     "Home and Garden": [
#         "Home Improvement 🛠️",
#         "Gardening 🌻",
#         "Interior Design 🏠",
#         "DIY 🔧",
#         "Decorating 🎨",
#     ],
#     "Humor": ["Comedy 🤣", "Satire 🕵️️", "Parody 🎭", "Jokes 😂", "Humorous Essays 📝"],
#     "Languages": [
#         "Spanish 🇪🇸",
#         "French 🇫🇷",
#         "German 🇩🇪",
#         "Italian 🇮🇹",
#         "Mandarin 🇨🇳",
#         "Japanese 🇯🇵",
#         "Russian 🇷🇺",
#         "Arabic 🇪🇬",
#         "English 🇬🇧",
#         "Sign Language 🤟",
#     ],
#     "Law": [
#         "Criminal Law 🚓",
#         "Constitutional Law 🗳️",
#         "Corporate Law 💼",
#         "Intellectual Property Law 💡",
#         "Tax Law 💰",
#         "International Law 🌍",
#         "Family Law 🏠",
#         "Employment Law 💼",
#         "Environmental Law 🌍",
#     ],
#     "Literature": [
#         "Classics 📚",
#         "World Literature 🌎",
#         "British Literature 🇬🇧",
#         "American Literature 🇺🇸",
#         "Drama 🎭",
#         "Poetry 🖋️",
#     ],
#     "Parenting": [
#         "Pregnancy 🤰",
#         "Childcare 🧒",
#         "Parent-Child Relationships 👨👧👦",
#         "Adoption 💕",
#         "Single Parenting 👨👧",
#         "Education 📚",
#     ],
#     "Pets": [
#         "Cats 🐱",
#         "Dogs 🐶",
#         "Birds 🦢",
#         "Fish 🐟",
#         "Reptiles 🐍",
#         "Horses 🐴",
#         "Small Animals 🐭",
#         "Veterinary Medicine 🐾",
#     ],
#     "Philosophy": [
#         "Epistemology 🤔",
#         "Logic 💡",
#         "Ethics 🕊️",
#         "Aesthetics 🎨",
#         "Political Philosophy 🗳️",
#         "Metaphysics 🌌",
#         "Ancient Philosophy 🏛️",
#         "Medieval Philosophy 📜",
#         "Renaissance Philosophy 🎨",
#         "Modern Philosophy 💻",
#     ],
#     "Reference": [
#         "Encyclopedias 📚",
#         "Dictionaries 💡",
#         "Thesauruses 🔍",
#         "Almanacs 📅",
#         "Atlases 🗺️",
#         "Handbooks 📖",
#         "Manuals 📚",
#     ],
#     "Self-Help": [
#         "Personal Growth 🌱",
#         "Motivation 💪",
#         "Self-Esteem 💕",
#         "Stress Management 💆️",
#         "Time Management ⏰",
#         "Creativity 🎨",
#         "Happiness 😊",
#         "Conflict Resolution 🤝",
#         "Communication Skills 🗣️",
#         "Leadership 🧔",
#     ],
#     "Social Science": [
#         "Anthropology 💬",
#         "Sociology 👥",
#         "Psychology 🧠",
#         "Political Science 🗳️",
#         "Economics 💰",
#         "Geography 🌎",
#         "Gender Studies 💪",
#         "Cultural Studies 🎨",
#         "Human Rights 🕊️",
#     ],
#     "Study Aids": [
#         "Test Preparation 💪",
#         "Study Guides 📚",
#         "Workbooks 📓",
#         "Flashcards 🃏",
#         "Reviews 🔍",
#     ],
#     "Technology": [
#         "Computer Science 💻",
#         "Programming 🔨",
#         "Web Development 🌐",
#         "Mobile Devices 📱",
#         "Computer Hardware 🖥️",
#         "Consumer Electronics 🔋",
#         "Artificial Intelligence 🤖",
#         "Data Science 📊",
#     ],
#     "Travel": [
#         "Africa 🌍",
#         "Asia 🌏",
#         "Australia and Oceania 🌴",
#         "Caribbean 🏝️",
#         "Central America 🌎",
#         "Europe 🇪🇺",
#         "Middle East 🌍",
#         "North America 🌎",
#         "South America 🌎",
#         "Specialty Travel 🧳",
#         "United States 🇺🇸",
#         "Food and Lodging 🍴",
#         "Guidebooks 🗺️",
#     ],
#     "Young Adult": [
#         "Science Fiction 🚀",
#         "Fantasy 🧝🏼",
#         "Realistic Fiction 💔",
#         "Horror 💀",
#         "Romance 💕",
#         "Mystery 🕵️️",
#         "Adventure 🧗️",
#         "Non-Fiction 📚",
#     ],
# }

book_categories = {
    "Fiction": [
        {"name": "Romance", "emoji": "💕"},
        {"name": "Science Fiction", "emoji": "🚀"},
        {"name": "Fantasy", "emoji": "🧚️"},
        {"name": "Mystery", "emoji": "🕵️️"},
        {"name": "Historical Fiction", "emoji": "🏰"},
        {"name": "Thriller", "emoji": "💥"},
        {"name": "Horror", "emoji": "👻"},
        {"name": "Drama", "emoji": "🎭"},
        {"name": "Comedy", "emoji": "😆"},
        {"name": "Crime", "emoji": "💰"},
        {"name": "Western", "emoji": "🤠"},
        {"name": "Short Story", "emoji": "📖"},
        {"name": "Classic", "emoji": "🧐"},
        {"name": "Contemporary", "emoji": "🕰️"},
        {"name": "LGBTQ+ Fiction", "emoji": "🏳️🌈"},
    ],
    "Non-Fiction": [
        {"name": "Biography", "emoji": "📖"},
        {"name": "History", "emoji": "🏛️"},
        {"name": "Science", "emoji": "🧪"},
        {"name": "Self-help", "emoji": "💪"},
        {"name": "Travel", "emoji": "🧳"},
        {"name": "Memoir", "emoji": "💭"},
        {"name": "Business", "emoji": "💼"},
        {"name": "Health and Wellness", "emoji": "🧘️"},
        {"name": "Cooking", "emoji": "🍴"},
        {"name": "Religion and Spirituality", "emoji": "🙏"},
        {"name": "Philosophy", "emoji": "🤔"},
        {"name": "Political Science", "emoji": "🗳️"},
        {"name": "Economics", "emoji": "💰"},
        {"name": "Journalism", "emoji": "📰"},
        {"name": "Education", "emoji": "🎓"},
        {"name": "Parenting", "emoji": "👪"},
        {"name": "Art", "emoji": "🎨"},
    ],
    "Children's Books": [
        {"name": "Picture Books", "emoji": "🖼️"},
        {"name": "Chapter Books", "emoji": "📚"},
        {"name": "Young Adult", "emoji": "🧔"},
        {"name": "Non-Fiction", "emoji": "💡"},
        {"name": "Board Books", "emoji": "📖"},
        {"name": "Early Readers", "emoji": "💡"},
        {"name": "Middle-Grade", "emoji": "🧒"},
        {"name": "Graphic Novels", "emoji": "📖"},
        {"name": "Poetry", "emoji": "💭"},
        {"name": "Activity Books", "emoji": "🎨"},
        {"name": "Coloring Books", "emoji": "🎨"},
        {"name": "Fairy Tales", "emoji": "🧚"},
        {"name": "Mythology", "emoji": "🧝"},
        {"name": "Folklore", "emoji": "👴️"},
    ],
    "Educational": [
        {"name": "Textbooks", "emoji": "📚"},
        {"name": "Study Guides", "emoji": "📚"},
        {"name": "Workbooks", "emoji": "💻"},
        {"name": "Test Prep", "emoji": "📊"},
        {"name": "Language Learning", "emoji": "🌎"},
        {"name": "Academic", "emoji": "🎓"},
        {"name": "Entrance Exam", "emoji": "🎓"},
        {"name": "Certification Exam", "emoji": "💼"},
        {"name": "College Guides", "emoji": "🎓"},
        {"name": "Career Guides", "emoji": "💼"},
        {"name": "Graduate School Guides", "emoji": "🎓"},
    ],
    "Professional and Technical": [
        {"name": "Medicine", "emoji": "💊"},
        {"name": "Law", "emoji": "💼"},
        {"name": "Business", "emoji": "💼"},
        {"name": "Engineering", "emoji": "🛠️"},
        {"name": "Computer Science", "emoji": "💻"},
        {"name": "Architecture", "emoji": "🏢"},
        {"name": "Agriculture", "emoji": "🌾"},
        {"name": "Environmental Science", "emoji": "🌍"},
        {"name": "Mathematics", "emoji": "🔢"},
        {"name": "Physics", "emoji": "🔬"},
        {"name": "Chemistry", "emoji": "🧪"},
        {"name": "Biology", "emoji": "🧬"},
        {"name": "Geography", "emoji": "🗺️"},
        {"name": "Astronomy", "emoji": "🚀"},
        {"name": "Earth Science", "emoji": "🌎"},
        {"name": "Social Science", "emoji": "🧠"},
    ],
    "Poetry": [
        {"name": "Classical Poetry", "emoji": "🎭"},
        {"name": "Modern Poetry", "emoji": "🎨"},
        {"name": "Haiku", "emoji": "🌿"},
        {"name": "Sonnet", "emoji": "🎶"},
        {"name": "Free verse", "emoji": "🎵"},
    ],
    "Photography": [
        {"name": "Landscape", "emoji": "🏞️"},
        {"name": "Portrait", "emoji": "📸"},
        {"name": "Wildlife", "emoji": "🐘"},
        {"name": "Action", "emoji": "💥"},
        {"name": "Street", "emoji": "🚶️"},
        {"name": "Fine Art", "emoji": "🎨"},
        {"name": "Commercial", "emoji": "💰"},
        {"name": "Underwater", "emoji": "🌊"},
        {"name": "Aerial", "emoji": "🛩️"},
        {"name": "Astrophotography", "emoji": "🌌"},
    ],
    "Art": [
        {"name": "Painting", "emoji": "🎨"},
        {"name": "Sculpture", "emoji": "💎"},
        {"name": "Drawing", "emoji": "🖍️"},
        {"name": "Printmaking", "emoji": "📰"},
        {"name": "Photography", "emoji": "📷"},
    ],
    "Religion and Spirituality": [
        {"name": "Buddhism", "emoji": "🧘"},
        {"name": "Christianity", "emoji": "✝️"},
        {"name": "Islam", "emoji": "🕋"},
        {"name": "Hinduism", "emoji": "🙏"},
        {"name": "Judaism", "emoji": "🕎"},
        {"name": "New Age", "emoji": "🌟"},
    ],
    "Science": [
        {"name": "Physics", "emoji": "🔬"},
        {"name": "Chemistry", "emoji": "🧪"},
        {"name": "Biology", "emoji": "🔬"},
        {"name": "Astronomy", "emoji": "🌌"},
        {"name": "Earth Science", "emoji": "🌍"},
        {"name": "Environmental Science", "emoji": "🌿"},
        {"name": "Technology", "emoji": "💻"},
        {"name": "Mathematics", "emoji": "📚"},
        {"name": "Computer Science", "emoji": "💻"},
    ],
    "Sports and Recreation": [
        {"name": "Fitness", "emoji": "🏋️️"},
        {"name": "Outdoor", "emoji": "🏕️"},
        {"name": "Team Sports", "emoji": "🏀"},
        {"name": "Individual Sports", "emoji": "🎾"},
        {"name": "Coaching", "emoji": "🏋️️"},
        {"name": "Extreme Sports", "emoji": "💥"},
        {"name": "Water Sports", "emoji": "🏊️"},
        {"name": "Winter Sports", "emoji": "⛷️"},
        {"name": "Equestrian", "emoji": "🐴"},
    ],
    "Comics and Graphic Novels": [
        {"name": "Superhero", "emoji": "🦸️"},
        {"name": "Science Fiction", "emoji": "🚀"},
        {"name": "Fantasy", "emoji": "🧝️"},
        {"name": "Historical", "emoji": "🏰"},
        {"name": "Horror", "emoji": "👻"},
    ],
    "Cookbooks": [
        {"name": "Regional", "emoji": "🌍"},
        {"name": "Cuisine", "emoji": "🍲"},
        {"name": "Special Diet", "emoji": "🥦"},
        {"name": "Cooking Techniques", "emoji": "🍴"},
        {"name": "Chefs", "emoji": "🍳"},
    ],
    "Crafts and Hobbies": [
        {"name": "Needlework", "emoji": "🧵"},
        {"name": "Woodworking", "emoji": "🔨"},
        {"name": "Home Improvement", "emoji": "🏠"},
        {"name": "Paper Craft", "emoji": "📝"},
        {"name": "Beading", "emoji": "💎"},
    ],
    "Dictionaries and Encyclopedias": [
        {"name": "General", "emoji": "📚"},
        {"name": "Specialized", "emoji": "💡"},
        {"name": "Foreign Language", "emoji": "🌎"},
        {"name": "Medical", "emoji": "💉"},
        {"name": "Technical", "emoji": "💻"},
    ],
    "Entertainment": [
        {"name": "Music", "emoji": "🎶"},
        {"name": "Movies", "emoji": "🎥"},
        {"name": "Television", "emoji": "📺"},
        {"name": "Awards", "emoji": "🎭"},
        {"name": "Humor", "emoji": "😂"},
    ],
    "Gay and Lesbian": [
        {"name": "Fiction", "emoji": "📖"},
        {"name": "Nonfiction", "emoji": "📚"},
        {"name": "Poetry", "emoji": "🖋️"},
        {"name": "Biography", "emoji": "🧔"},
        {"name": "Autobiography", "emoji": "💬"},
    ],
    "Health and Medicine": [
        {"name": "Diseases", "emoji": "🦠"},
        {"name": "Disorders", "emoji": "🤕"},
        {"name": "Drug Guides", "emoji": "💊"},
        {"name": "First Aid", "emoji": "🚑"},
        {"name": "Health Policy", "emoji": "💊"},
    ],
    "History": [
        {"name": "World", "emoji": "🌍"},
        {"name": "European", "emoji": "🇪🇺"},
        {"name": "American", "emoji": "🇺🇸"},
        {"name": "Ancient", "emoji": "🏺"},
        {"name": "Medieval", "emoji": "🏰"},
        {"name": "Military", "emoji": "💂️"},
    ],
    "Home and Garden": [
        {"name": "Home Improvement", "emoji": "🛠️"},
        {"name": "Gardening", "emoji": "🌻"},
        {"name": "Interior Design", "emoji": "🏠"},
        {"name": "DIY", "emoji": "🔧"},
        {"name": "Decorating", "emoji": "🎨"},
    ],
    "Humor": [
        {"name": "Comedy", "emoji": "🤣"},
        {"name": "Satire", "emoji": "🕵️️"},
        {"name": "Parody", "emoji": "🎭"},
        {"name": "Jokes", "emoji": "😂"},
        {"name": "Humorous Essays", "emoji": "📝"},
    ],
    "Languages": [
        {"name": "Spanish", "emoji": "🇪🇸"},
        {"name": "French", "emoji": "🇫🇷"},
        {"name": "German", "emoji": "🇩🇪"},
        {"name": "Italian", "emoji": "🇮🇹"},
        {"name": "Mandarin", "emoji": "🇨🇳"},
        {"name": "Japanese", "emoji": "🇯🇵"},
        {"name": "Russian", "emoji": "🇷🇺"},
        {"name": "Arabic", "emoji": "🇪🇬"},
        {"name": "English", "emoji": "🇬🇧"},
        {"name": "Sign Language", "emoji": "🤟"},
    ],
    "Law": [
        {"name": "Criminal Law", "emoji": "🚓"},
        {"name": "Constitutional Law", "emoji": "🗳️"},
        {"name": "Corporate Law", "emoji": "💼"},
        {"name": "Intellectual Property Law", "emoji": "💡"},
        {"name": "Tax Law", "emoji": "💰"},
        {"name": "International Law", "emoji": "🌍"},
        {"name": "Family Law", "emoji": "🏠"},
        {"name": "Employment Law", "emoji": "💼"},
        {"name": "Environmental Law", "emoji": " 🌍"},
    ],
    "Literature": [
        {"name": "Classics", "emoji": "📚"},
        {"name": "World Literature", "emoji": "🌎"},
        {"name": "British Literature", "emoji": "🇬🇧"},
        {"name": "American Literature", "emoji": "🇺🇸"},
        {"name": "Drama", "emoji": "🎭"},
        {"name": "Poetry", "emoji": "🖋️"},
    ],
    "Parenting": [
        {"name": "Pregnancy", "emoji": "🤰"},
        {"name": "Childcare", "emoji": "🧒"},
        {"name": "Parent-Child Relationships", "emoji": "👨👧👦"},
        {"name": "Adoption", "emoji": "💕"},
        {"name": "Single Parenting", "emoji": "👨👧"},
        {"name": "Education", "emoji": "📚"},
    ],
    "Pets": [
        {"name": "Cats", "emoji": "🐱"},
        {"name": "Dogs", "emoji": "🐶"},
        {"name": "Birds", "emoji": "🦢"},
        {"name": "Fish", "emoji": "🐟"},
        {"name": "Reptiles", "emoji": "🐍"},
        {"name": "Horses", "emoji": "🐴"},
        {"name": "Small Animals", "emoji": "🐭"},
        {"name": "Veterinary Medicine", "emoji": "🐾"},
    ],
    "Philosophy": [
        {"name": "Epistemology", "emoji": "🤔"},
        {"name": "Logic", "emoji": "💡"},
        {"name": "Ethics", "emoji": "🕊️"},
        {"name": "Aesthetics", "emoji": "🎨"},
        {"name": "Political Philosophy", "emoji": "🗳️"},
        {"name": "Metaphysics", "emoji": "🌌"},
        {"name": "Ancient Philosophy", "emoji": "🏛️"},
        {"name": "Medieval Philosophy", "emoji": "📜"},
        {"name": "Renaissance Philosophy", "emoji": "🎨"},
        {"name": "Modern Philosophy", "emoji": "💻"},
    ],
    "Reference": [
        {"name": "Encyclopedias", "emoji": "📚"},
        {"name": "Dictionaries", "emoji": "💡"},
        {"name": "Thesauruses", "emoji": "🔍"},
        {"name": "Almanacs", "emoji": "📅"},
        {"name": "Atlases", "emoji": "🗺️"},
        {"name": "Handbooks", "emoji": "📖"},
        {"name": "Manuals", "emoji": "📚"},
    ],
    "Self-Help": [
        {"name": "Personal Growth", "emoji": "🌱"},
        {"name": "Motivation", "emoji": "💪"},
        {"name": "Self-Esteem", "emoji": "💕"},
        {"name": "Stress Management", "emoji": "💆️"},
        {"name": "Time Management", "emoji": "⏰"},
        {"name": "Creativity", "emoji": "🎨"},
        {"name": "Happiness", "emoji": "😊"},
        {"name": "Conflict Resolution", "emoji": "🤝"},
        {"name": "Communication Skills", "emoji": "🗣️"},
        {"name": "Leadership", "emoji": "🧔"},
    ],
    "Social Science": [
        {"name": "Anthropology", "emoji": "💬"},
        {"name": "Sociology", "emoji": "👥"},
        {"name": "Psychology", "emoji": "🧠"},
        {"name": "Political Science", "emoji": "🗳️"},
        {"name": "Economics", "emoji": "💰"},
        {"name": "Geography", "emoji": "🌎"},
        {"name": "Gender Studies", "emoji": "💪"},
        {"name": "Cultural Studies", "emoji": "🎨"},
        {"name": "Human Rights", "emoji": "🕊️"},
    ],
    "Study Aids": [
        {"name": "Test Preparation", "emoji": "💪"},
        {"name": "Study Guides", "emoji": "📚"},
        {"name": "Workbooks", "emoji": "📓"},
        {"name": "Flashcards", "emoji": "🃏"},
        {"name": "Reviews", "emoji": "🔍"},
    ],
    "Technology": [
        {"name": "Computer Science", "emoji": "💻"},
        {"name": "Programming", "emoji": "🔨"},
        {"name": "Web Development", "emoji": "🌐"},
        {"name": "Mobile Devices", "emoji": "📱"},
        {"name": "Computer Hardware", "emoji": "🖥️"},
        {"name": "Consumer Electronics", "emoji": "🔋"},
        {"name": "Artificial Intelligence", "emoji": "🤖"},
        {"name": "Data Science", "emoji": "📊"},
    ],
    "Travel": [
        {"name": "Africa", "emoji": "🌍"},
        {"name": "Asia", "emoji": "🌏"},
        {"name": "Australia and Oceania", "emoji": "🌴"},
        {"name": "Caribbean", "emoji": "🏝️"},
        {"name": "Central America", "emoji": "🌎"},
        {"name": "Europe", "emoji": "🇪🇺"},
        {"name": "Middle East", "emoji": "🌍"},
        {"name": "North America", "emoji": "🌎"},
        {"name": "South America", "emoji": "🌎"},
        {"name": "Specialty Travel", "emoji": "🧳"},
        {"name": "United States", "emoji": "🇺🇸"},
        {"name": "Food and Lodging", "emoji": "🍴"},
        {"name": "Guidebooks", "emoji": "🗺️"},
    ],
    "Young Adult": [
        {"name": "Science Fiction", "emoji": "🚀"},
        {"name": "Fantasy", "emoji": "🧝🏼"},
        {"name": "Realistic Fiction", "emoji": "💔"},
        {"name": "Horror", "emoji": "💀"},
        {"name": "Romance", "emoji": "💕"},
        {"name": "Mystery", "emoji": "🕵️️"},
        {"name": "Adventure", "emoji": "🧗️"},
        {"name": "Non-Fiction", "emoji": "📚"},
    ],
}


def get_categories() -> str:
    return json.dumps(book_categories)


if __name__ == "__main__":
    new_items = {}
    for k, v in book_categories.items():
        new_list = [
            {"name": sub["name"].rstrip(" "), "emoji": sub["emoji"]} for sub in v
        ]
        new_items[k] = new_list
    print(new_items)
