import json

book_categories = {
    "Fiction": [
        "Romance",
        "Science Fiction",
        "Fantasy",
        "Mystery",
        "Historical Fiction",
        "Thriller",
        "Horror",
        "Drama",
        "Comedy",
        "Crime",
        "Western",
        "Short Story",
        "Classic",
        "Contemporary",
        "LGBTQ+ Fiction",
    ],
    "Non-Fiction": [
        "Biography",
        "History",
        "Science",
        "Self-help",
        "Travel",
        "Memoir",
        "Business",
        "Health and Wellness",
        "Cooking",
        "Religion and Spirituality",
        "Philosophy",
        "Political Science",
        "Economics",
        "Journalism",
        "Education",
        "Parenting",
        "Art",
    ],
    "Children's Books": [
        "Picture Books",
        "Chapter Books",
        "Young Adult",
        "Non-Fiction",
        "Board Books",
        "Early Readers",
        "Middle-Grade",
        "Graphic Novels",
        "Poetry",
        "Activity Books",
        "Coloring Books",
        "Fairy Tales",
        "Mythology",
        "Folklore",
    ],
    "Educational": [
        "Textbooks",
        "Study Guides",
        "Workbooks",
        "Test Prep",
        "Language Learning",
        "Academic",
        "Entrance Exam",
        "Certification Exam",
        "College Guides",
        "Career Guides",
        "Graduate School Guides",
    ],
    "Professional and Technical": [
        "Medicine",
        "Law",
        "Business",
        "Engineering",
        "Computer Science",
        "Architecture",
        "Agriculture",
        "Environmental Science",
        "Mathematics",
        "Physics",
        "Chemistry",
        "Biology",
        "Geography",
        "Astronomy",
        "Earth Science",
        "Social Science",
    ],
    "Poetry": ["Classical Poetry", "Modern Poetry", "Haiku", "Sonnet", "Free verse"],
    "Photography": [
        "Landscape",
        "Portrait",
        "Wildlife",
        "Action",
        "Street",
        "Fine Art",
        "Commercial",
        "Underwater",
        "Aerial",
        "Astrophotography",
    ],
    "Art": ["Painting", "Sculpture", "Drawing", "Printmaking", "Photography"],
    "Religion and Spirituality": [
        "Buddhism",
        "Christianity",
        "Islam",
        "Hinduism",
        "Judaism",
        "New Age",
    ],
    "Science": [
        "Physics",
        "Chemistry",
        "Biology",
        "Astronomy",
        "Earth Science",
        "Environmental Science",
        "Technology",
        "Mathematics",
        "Computer Science",
    ],
    "Sports and Recreation": [
        "Fitness",
        "Outdoor",
        "Team Sports",
        "Individual Sports",
        "Coaching",
        "Extreme Sports",
        "Water Sports",
        "Winter Sports",
        "Equestrian",
    ],
    "Comics and Graphic Novels": [
        "Superhero",
        "Science Fiction",
        "Fantasy",
        "Historical",
        "Horror",
    ],
    "Cookbooks": ["Regional", "Cuisine", "Special Diet", "Cooking Techniques", "Chefs"],
    "Crafts and Hobbies": [
        "Needlework",
        "Woodworking",
        "Home Improvement",
        "Paper Craft",
        "Beading",
    ],
    "Dictionaries and Encyclopedias": [
        "General",
        "Specialized",
        "Foreign Language",
        "Medical",
        "Technical",
    ],
    "Entertainment": ["Music", "Movies", "Television", "Awards", "Humor"],
    "Gay and Lesbian": [
        "Fiction",
        "Nonfiction",
        "Poetry",
        "Biography",
        "Autobiography",
    ],
    "Health and Medicine": [
        "Diseases",
        "Disorders",
        "Drug Guides",
        "First Aid",
        "Health Policy",
    ],
    "History": ["World", "European", "American", "Ancient", "Medieval", "Military"],
    "Home and Garden": [
        "Home Improvement",
        "Gardening",
        "Interior Design",
        "DIY",
        "Decorating",
    ],
    "Humor": ["Comedy", "Satire", "Parody", "Jokes", "Humorous Essays"],
    "Languages": [
        "Spanish",
        "French",
        "German",
        "Italian",
        "Mandarin",
        "Japanese",
        "Russian",
        "Arabic",
        "English",
        "Sign Language",
    ],
    "Law": [
        "Criminal Law",
        "Constitutional Law",
        "Corporate Law",
        "Intellectual Property Law",
        "Tax Law",
        "International Law",
        "Family Law",
        "Employment Law",
        "Environmental Law",
    ],
    "Literature": [
        "Classics",
        "World Literature",
        "British Literature",
        "American Literature",
        "Drama",
        "Poetry",
    ],
    "Parenting": [
        "Pregnancy",
        "Childcare",
        "Parent-Child Relationships",
        "Adoption",
        "Single Parenting",
        "Education",
    ],
    "Pets": [
        "Cats",
        "Dogs",
        "Birds",
        "Fish",
        "Reptiles",
        "Horses",
        "Small Animals",
        "Veterinary Medicine",
    ],
    "Philosophy": [
        "Epistemology",
        "Logic",
        "Ethics",
        "Aesthetics",
        "Political Philosophy",
        "Metaphysics",
        "Ancient Philosophy",
        "Medieval Philosophy",
        "Renaissance Philosophy",
        "Modern Philosophy",
    ],
    "Reference": [
        "Encyclopedias",
        "Dictionaries",
        "Thesauruses",
        "Almanacs",
        "Atlases",
        "Handbooks",
        "Manuals",
    ],
    "Self-Help": [
        "Personal Growth",
        "Motivation",
        "Self-Esteem",
        "Stress Management",
        "Time Management",
        "Creativity",
        "Happiness",
        "Conflict Resolution",
        "Communication Skills",
        "Leadership",
    ],
    "Social Science": [
        "Anthropology",
        "Sociology",
        "Psychology",
        "Political Science",
        "Economics",
        "Geography",
        "Gender Studies",
        "Cultural Studies",
        "Human Rights",
    ],
    "Study Aids": [
        "Test Preparation",
        "Study Guides",
        "Workbooks",
        "Flashcards",
        "Reviews",
    ],
    "Technology": [
        "Computer Science",
        "Programming",
        "Web Development",
        "Mobile Devices",
        "Computer Hardware",
        "Consumer Electronics",
        "Artificial Intelligence",
        "Data Science",
    ],
    "Travel": [
        "Africa",
        "Asia",
        "Australia and Oceania",
        "Caribbean",
        "Central America",
        "Europe",
        "Middle East",
        "North America",
        "South America",
        "Specialty Travel",
        "United States",
        "Food and Lodging",
        "Guidebooks",
    ],
    "Young Adult": [
        "Science Fiction",
        "Fantasy",
        "Realistic Fiction",
        "Horror",
        "Romance",
        "Mystery",
        "Adventure",
        "Non-Fiction",
    ],
}


def get_categories() -> str:
    return json.dumps(book_categories)
