book_categories = {
    "Fiction": [
        {"name": "Romance", "emoji": "💕"},
        {"name": "Science Fiction", "emoji": "🚀"},
        {"name": "Fantasy", "emoji": "🧚️"},
        {"name": "Mystery", "emoji": "🕵️️"},
        {"name": "Historical Fiction", "emoji": "🏰"},
        {"name": "Thriller", "emoji": "💥"},
        {"name": "Horror", "emoji": "👻"},
        {"name": "Drama", "emoji": "🎭"},
        {"name": "Comedy", "emoji": "😆"},
        {"name": "Crime", "emoji": "💰"},
        {"name": "Western", "emoji": "🤠"},
        {"name": "Short Story", "emoji": "📖"},
        {"name": "Classic", "emoji": "🧐"},
        {"name": "Contemporary", "emoji": "🕰️"},
        {"name": "LGBTQ+ Fiction", "emoji": "🌈"},
    ],
    "Non-Fiction": [
        {"name": "Biography", "emoji": "📖"},
        {"name": "History", "emoji": "🏛️"},
        {"name": "Science", "emoji": "🧪"},
        {"name": "Self-help", "emoji": "💪"},
        {"name": "Travel", "emoji": "🧳"},
        {"name": "Memoir", "emoji": "💭"},
        {"name": "Business", "emoji": "💼"},
        {"name": "Health and Wellness", "emoji": "🧘️"},
        {"name": "Cooking", "emoji": "🍴"},
        {"name": "Religion and Spirituality", "emoji": "🙏"},
        {"name": "Philosophy", "emoji": "🤔"},
        {"name": "Political Science", "emoji": "🗳️"},
        {"name": "Economics", "emoji": "💰"},
        {"name": "Journalism", "emoji": "📰"},
        {"name": "Education", "emoji": "🎓"},
        {"name": "Parenting", "emoji": "👪"},
        {"name": "Art", "emoji": "🎨"},
    ],
    "Art": [
        {"name": "Painting", "emoji": "🎨"},
        {"name": "Sculpture", "emoji": "💎"},
        {"name": "Drawing", "emoji": "🖍️"},
        {"name": "Printmaking", "emoji": "📰"},
        {"name": "Photography", "emoji": "📷"},
    ],
    "Children's Books": [
        {"name": "Picture Books", "emoji": "🖼️"},
        {"name": "Chapter Books", "emoji": "📚"},
        {"name": "Young Adult", "emoji": "🧔"},
        {"name": "Non-Fiction", "emoji": "💡"},
        {"name": "Board Books", "emoji": "📖"},
        {"name": "Early Readers", "emoji": "💡"},
        {"name": "Middle-Grade", "emoji": "🧒"},
        {"name": "Graphic Novels", "emoji": "📖"},
        {"name": "Poetry", "emoji": "💭"},
        {"name": "Activity Books", "emoji": "🎨"},
        {"name": "Coloring Books", "emoji": "🎨"},
        {"name": "Fairy Tales", "emoji": "🧚"},
        {"name": "Mythology", "emoji": "🧝"},
        {"name": "Folklore", "emoji": "👴️"},
    ],
    "Comics and Graphic Novels": [
        {"name": "Superhero", "emoji": "🦸️"},
        {"name": "Science Fiction", "emoji": "🚀"},
        {"name": "Fantasy", "emoji": "🧝️"},
        {"name": "Historical", "emoji": "🏰"},
        {"name": "Horror", "emoji": "👻"},
    ],
    "Cookbooks": [
        {"name": "Regional", "emoji": "🌍"},
        {"name": "Cuisine", "emoji": "🍲"},
        {"name": "Special Diet", "emoji": "🥦"},
        {"name": "Cooking Techniques", "emoji": "🍴"},
        {"name": "Chefs", "emoji": "🍳"},
    ],
    "Crafts and Hobbies": [
        {"name": "Needlework", "emoji": "🧵"},
        {"name": "Woodworking", "emoji": "🔨"},
        {"name": "Home Improvement", "emoji": "🏠"},
        {"name": "Paper Craft", "emoji": "📝"},
        {"name": "Beading", "emoji": "💎"},
    ],
    "Dictionaries and Encyclopedias": [
        {"name": "General", "emoji": "📚"},
        {"name": "Specialized", "emoji": "💡"},
        {"name": "Foreign Language", "emoji": "🌎"},
        {"name": "Medical", "emoji": "💉"},
        {"name": "Technical", "emoji": "💻"},
    ],
    "Educational": [
        {"name": "Textbooks", "emoji": "📚"},
        {"name": "Study Guides", "emoji": "📚"},
        {"name": "Workbooks", "emoji": "💻"},
        {"name": "Test Prep", "emoji": "📊"},
        {"name": "Language Learning", "emoji": "🌎"},
        {"name": "Academic", "emoji": "🎓"},
        {"name": "Entrance Exam", "emoji": "🎓"},
        {"name": "Certification Exam", "emoji": "💼"},
        {"name": "College Guides", "emoji": "🎓"},
        {"name": "Career Guides", "emoji": "💼"},
        {"name": "Graduate School Guides", "emoji": "🎓"},
    ],
    "Entertainment": [
        {"name": "Music", "emoji": "🎶"},
        {"name": "Movies", "emoji": "🎥"},
        {"name": "Television", "emoji": "📺"},
        {"name": "Awards", "emoji": "🎭"},
        {"name": "Humor", "emoji": "😂"},
    ],
    "Health and Medicine": [
        {"name": "Diseases", "emoji": "🦠"},
        {"name": "Disorders", "emoji": "🤕"},
        {"name": "Drug Guides", "emoji": "💊"},
        {"name": "First Aid", "emoji": "🚑"},
        {"name": "Health Policy", "emoji": "💊"},
    ],
    "History": [
        {"name": "World", "emoji": "🌍"},
        {"name": "European", "emoji": "🇪🇺"},
        {"name": "American", "emoji": "🇺🇸"},
        {"name": "Ancient", "emoji": "🏺"},
        {"name": "Medieval", "emoji": "🏰"},
        {"name": "Military", "emoji": "💂️"},
    ],
    "Home and Garden": [
        {"name": "Home Improvement", "emoji": "🛠️"},
        {"name": "Gardening", "emoji": "🌻"},
        {"name": "Interior Design", "emoji": "🏠"},
        {"name": "DIY", "emoji": "🔧"},
        {"name": "Decorating", "emoji": "🎨"},
    ],
    "Humor": [
        {"name": "Comedy", "emoji": "🤣"},
        {"name": "Satire", "emoji": "🕵️️"},
        {"name": "Parody", "emoji": "🎭"},
        {"name": "Jokes", "emoji": "😂"},
        {"name": "Humorous Essays", "emoji": "📝"},
    ],
    "LGBTQ+": [
        {"name": "Fiction", "emoji": "📖"},
        {"name": "Nonfiction", "emoji": "📚"},
        {"name": "Poetry", "emoji": "🖋️"},
        {"name": "Biography", "emoji": "🧔"},
        {"name": "Autobiography", "emoji": "💬"},
    ],
    "Languages": [
        {"name": "Spanish", "emoji": "🇪🇸"},
        {"name": "French", "emoji": "🇫🇷"},
        {"name": "German", "emoji": "🇩🇪"},
        {"name": "Italian", "emoji": "🇮🇹"},
        {"name": "Mandarin", "emoji": "🇨🇳"},
        {"name": "Japanese", "emoji": "🇯🇵"},
        {"name": "Russian", "emoji": "🇷🇺"},
        {"name": "Arabic", "emoji": "🇪🇬"},
        {"name": "English", "emoji": "🇬🇧"},
        {"name": "Sign Language", "emoji": "🤟"},
    ],
    "Law": [
        {"name": "Criminal Law", "emoji": "🚓"},
        {"name": "Constitutional Law", "emoji": "🗳️"},
        {"name": "Corporate Law", "emoji": "💼"},
        {"name": "Intellectual Property Law", "emoji": "💡"},
        {"name": "Tax Law", "emoji": "💰"},
        {"name": "International Law", "emoji": "🌍"},
        {"name": "Family Law", "emoji": "🏠"},
        {"name": "Employment Law", "emoji": "💼"},
        {"name": "Environmental Law", "emoji": " 🌍"},
    ],
    "Literature": [
        {"name": "Classics", "emoji": "📚"},
        {"name": "World Literature", "emoji": "🌎"},
        {"name": "British Literature", "emoji": "🇬🇧"},
        {"name": "American Literature", "emoji": "🇺🇸"},
        {"name": "Drama", "emoji": "🎭"},
        {"name": "Poetry", "emoji": "🖋️"},
    ],
    "Parenting": [
        {"name": "Pregnancy", "emoji": "🤰"},
        {"name": "Childcare", "emoji": "🧒"},
        {"name": "Parent-Child Relationships", "emoji": "👨👧👦"},
        {"name": "Adoption", "emoji": "💕"},
        {"name": "Single Parenting", "emoji": "👨👧"},
        {"name": "Education", "emoji": "📚"},
    ],
    "Pets": [
        {"name": "Cats", "emoji": "🐱"},
        {"name": "Dogs", "emoji": "🐶"},
        {"name": "Birds", "emoji": "🦢"},
        {"name": "Fish", "emoji": "🐟"},
        {"name": "Reptiles", "emoji": "🐍"},
        {"name": "Horses", "emoji": "🐴"},
        {"name": "Small Animals", "emoji": "🐭"},
        {"name": "Veterinary Medicine", "emoji": "🐾"},
    ],
    "Philosophy": [
        {"name": "Epistemology", "emoji": "🤔"},
        {"name": "Logic", "emoji": "💡"},
        {"name": "Ethics", "emoji": "🕊️"},
        {"name": "Aesthetics", "emoji": "🎨"},
        {"name": "Political Philosophy", "emoji": "🗳️"},
        {"name": "Metaphysics", "emoji": "🌌"},
        {"name": "Ancient Philosophy", "emoji": "🏛️"},
        {"name": "Medieval Philosophy", "emoji": "📜"},
        {"name": "Renaissance Philosophy", "emoji": "🎨"},
        {"name": "Modern Philosophy", "emoji": "💻"},
    ],
    "Photography": [
        {"name": "Landscape", "emoji": "🏞️"},
        {"name": "Portrait", "emoji": "📸"},
        {"name": "Wildlife", "emoji": "🐘"},
        {"name": "Action", "emoji": "💥"},
        {"name": "Street", "emoji": "🚶️"},
        {"name": "Fine Art", "emoji": "🎨"},
        {"name": "Commercial", "emoji": "💰"},
        {"name": "Underwater", "emoji": "🌊"},
        {"name": "Aerial", "emoji": "🛩️"},
        {"name": "Astrophotography", "emoji": "🌌"},
    ],
    "Poetry": [
        {"name": "Classical Poetry", "emoji": "🎭"},
        {"name": "Modern Poetry", "emoji": "🎨"},
        {"name": "Haiku", "emoji": "🌿"},
        {"name": "Sonnet", "emoji": "🎶"},
        {"name": "Free verse", "emoji": "🎵"},
    ],
    "Professional and Technical": [
        {"name": "Medicine", "emoji": "💊"},
        {"name": "Law", "emoji": "💼"},
        {"name": "Business", "emoji": "💼"},
        {"name": "Engineering", "emoji": "🛠️"},
        {"name": "Computer Science", "emoji": "💻"},
        {"name": "Architecture", "emoji": "🏢"},
        {"name": "Agriculture", "emoji": "🌾"},
        {"name": "Environmental Science", "emoji": "🌍"},
        {"name": "Mathematics", "emoji": "🔢"},
        {"name": "Physics", "emoji": "🔬"},
        {"name": "Chemistry", "emoji": "🧪"},
        {"name": "Biology", "emoji": "🧬"},
        {"name": "Geography", "emoji": "🗺️"},
        {"name": "Astronomy", "emoji": "🚀"},
        {"name": "Earth Science", "emoji": "🌎"},
        {"name": "Social Science", "emoji": "🧠"},
    ],
    "Reference": [
        {"name": "Encyclopedias", "emoji": "📚"},
        {"name": "Dictionaries", "emoji": "💡"},
        {"name": "Thesauruses", "emoji": "🔍"},
        {"name": "Almanacs", "emoji": "📅"},
        {"name": "Atlases", "emoji": "🗺️"},
        {"name": "Handbooks", "emoji": "📖"},
        {"name": "Manuals", "emoji": "📚"},
    ],
    "Religion and Spirituality": [
        {"name": "Buddhism", "emoji": "🧘"},
        {"name": "Christianity", "emoji": "✝️"},
        {"name": "Islam", "emoji": "🕋"},
        {"name": "Hinduism", "emoji": "🙏"},
        {"name": "Judaism", "emoji": "🕎"},
        {"name": "New Age", "emoji": "🌟"},
    ],
    "Science": [
        {"name": "Physics", "emoji": "🔬"},
        {"name": "Chemistry", "emoji": "🧪"},
        {"name": "Biology", "emoji": "🔬"},
        {"name": "Astronomy", "emoji": "🌌"},
        {"name": "Earth Science", "emoji": "🌍"},
        {"name": "Environmental Science", "emoji": "🌿"},
        {"name": "Technology", "emoji": "💻"},
        {"name": "Mathematics", "emoji": "📚"},
        {"name": "Computer Science", "emoji": "💻"},
    ],
    "Self-Help": [
        {"name": "Personal Growth", "emoji": "🌱"},
        {"name": "Motivation", "emoji": "💪"},
        {"name": "Self-Esteem", "emoji": "💕"},
        {"name": "Stress Management", "emoji": "💆️"},
        {"name": "Time Management", "emoji": "⏰"},
        {"name": "Creativity", "emoji": "🎨"},
        {"name": "Happiness", "emoji": "😊"},
        {"name": "Conflict Resolution", "emoji": "🤝"},
        {"name": "Communication Skills", "emoji": "🗣️"},
        {"name": "Leadership", "emoji": "🧔"},
    ],
    "Social Science": [
        {"name": "Anthropology", "emoji": "💬"},
        {"name": "Sociology", "emoji": "👥"},
        {"name": "Psychology", "emoji": "🧠"},
        {"name": "Political Science", "emoji": "🗳️"},
        {"name": "Economics", "emoji": "💰"},
        {"name": "Geography", "emoji": "🌎"},
        {"name": "Gender Studies", "emoji": "💪"},
        {"name": "Cultural Studies", "emoji": "🎨"},
        {"name": "Human Rights", "emoji": "🕊️"},
    ],
    "Sports and Recreation": [
        {"name": "Fitness", "emoji": "🏋️️"},
        {"name": "Outdoor", "emoji": "🏕️"},
        {"name": "Team Sports", "emoji": "🏀"},
        {"name": "Individual Sports", "emoji": "🎾"},
        {"name": "Coaching", "emoji": "🏋️️"},
        {"name": "Extreme Sports", "emoji": "💥"},
        {"name": "Water Sports", "emoji": "🏊️"},
        {"name": "Winter Sports", "emoji": "⛷️"},
        {"name": "Equestrian", "emoji": "🐴"},
    ],
    "Study Aids": [
        {"name": "Test Preparation", "emoji": "💪"},
        {"name": "Study Guides", "emoji": "📚"},
        {"name": "Workbooks", "emoji": "📓"},
        {"name": "Flashcards", "emoji": "🃏"},
        {"name": "Reviews", "emoji": "🔍"},
    ],
    "Technology": [
        {"name": "Computer Science", "emoji": "💻"},
        {"name": "Programming", "emoji": "🔨"},
        {"name": "Web Development", "emoji": "🌐"},
        {"name": "Mobile Devices", "emoji": "📱"},
        {"name": "Computer Hardware", "emoji": "🖥️"},
        {"name": "Consumer Electronics", "emoji": "🔋"},
        {"name": "Artificial Intelligence", "emoji": "🤖"},
        {"name": "Data Science", "emoji": "📊"},
    ],
    "Travel": [
        {"name": "Africa", "emoji": "🌍"},
        {"name": "Asia", "emoji": "🌏"},
        {"name": "Australia and Oceania", "emoji": "🌴"},
        {"name": "Caribbean", "emoji": "🏝️"},
        {"name": "Central America", "emoji": "🌎"},
        {"name": "Europe", "emoji": "🇪🇺"},
        {"name": "Middle East", "emoji": "🌍"},
        {"name": "North America", "emoji": "🌎"},
        {"name": "South America", "emoji": "🌎"},
        {"name": "Specialty Travel", "emoji": "🧳"},
        {"name": "United States", "emoji": "🇺🇸"},
        {"name": "Food and Lodging", "emoji": "🍴"},
        {"name": "Guidebooks", "emoji": "🗺️"},
    ],
    "Young Adult": [
        {"name": "Science Fiction", "emoji": "🚀"},
        {"name": "Fantasy", "emoji": "🧝🏼"},
        {"name": "Realistic Fiction", "emoji": "💔"},
        {"name": "Horror", "emoji": "💀"},
        {"name": "Romance", "emoji": "💕"},
        {"name": "Mystery", "emoji": "🕵️️"},
        {"name": "Adventure", "emoji": "🧗️"},
        {"name": "Non-Fiction", "emoji": "📚"},
    ],
}
